package WordleSolver;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;
import java.util.Scanner;

public class WordleGame implements Wordle {

    private ArrayList<String> knownWords;
    private String secretWord;
    private Random rnd = new Random(); // a source of random numbers

    public WordleGame(String file, int length, long minfreq, long maxfreq) throws IOException {
        // ~12K 5 letter words with min frequency of 100,000
        loadWords(file, length, minfreq, maxfreq);
    }

    public WordleGame(String[] words) {
        // Constructor: instantiates knownWords and adds words from parameter if same length as first word.
        knownWords = new ArrayList<>();
        knownWords.add(words[0].toLowerCase()); // Adds first word in array to compare others to.

        for (int i = 1; i < words.length; i++) {
            if (words[i].length() == words[0].length()) {
                knownWords.add(words[i].toLowerCase());
            }
        }
    }

    @Override
    public int getRules() {
        // Returns the int zero for only allowing words from known words as a guess.
        return 0;
    }

    public int numberOfKnownWords() { return knownWords.size(); } // For testing.

    public String getSecretWord() { return secretWord; }          // For testing.

    public void loadWords(String filenm, int length, long minfreq, long maxfreq) throws IOException {
        // Scans each line of file and adds the word to known words list if correct length and within range specified.
        knownWords = new ArrayList<>();
        Scanner fileScanner = new Scanner(new File(filenm));

        while (fileScanner.hasNext()) {
            String wordToken = fileScanner.next();
            long freqToken = fileScanner.nextLong();
            if (wordToken.length() == length && freqToken >= minfreq) {
                if (maxfreq != 0) {
                    if (freqToken <= maxfreq) knownWords.add(wordToken.toLowerCase());
                } else knownWords.add(wordToken.toLowerCase()); // If maxFreq is 0, no upper limit.
            }
        }
        fileScanner.close();
    }

    public void printNum(String fname, int freq, int len) {
        // Used for testing. Prints all words from file that match parameters.
        try {
            Scanner scanner = new Scanner(new File(fname));
            while (scanner.hasNext()) {
                String token = scanner.next();
                long freqToken = scanner.nextLong();
                if (token.length() == len && freqToken > freq) System.out.println(token);
            }
            scanner.close();
        } catch (FileNotFoundException e) {
            System.out.println("An Error Occurred");
            e.printStackTrace();
        }
    }

    public ArrayList<String> getKnownWords() { return new ArrayList<>(knownWords); } // For testing.

    public void initGame() {
        Random r = new Random();
        secretWord = knownWords.get(r.nextInt(knownWords.size())); // sets secret word randomly.
    }

    public void initGame(String secret) { // Overloaded method for WordleBotTests. Able to set secret word manually.
        secretWord = secret;
    } // overloaded initgame for BasicWordleBotTests.

    public Hint guess(String g) {
        // Returns a Hint constructor call, passing the guess (token) and secret word as arguments.
        int length = secretWord.length();
        if (length != g.length()) {
            throw new IllegalArgumentException("Wrong length guess!");
        }
        return new HintGenerator(g, secretWord);
    }
}

class HintGenerator implements Hint {

    // why private?
    // because we want the hint to be generated by the constructor and then
    // not messed with further. So, we restrict access to these variables.
    private String correctlyPlaced;
    private String incorrectlyPlaced;
    private String notInPuzzle;
    private String guess;

    /*
    For the correctlyPlaced and incorrectlyPlaced instance variables (Hints) I used char[] because this made it much
    easier for indexing since char[]'s have set sizes and the indexing does not change as you add elements to it like
    ArrayLists do. Concatenation using "+" would have been much more difficult as well since this would require adding
    elements in order from left to right as they occur instead of searching for correctly placed letters first, then
    incorrectly placed ones next, etc. For example, a char[] allowed me to loop through the guess and secret word and
    place the letters that were in the correct location (or incorrect location) in the same exact index as the guess/
    secret word since the char[] had the same size and the indexing was fixed.

    For the notInPuzzle variable I decided to use a StringBuilder object. I chose this since this variable didn't need
    to be the same size (needed to be <= secret word length) as the secret word/guess and the StringBuilder doesn't need
    a defined size when you instantiate it. Also, fixed indices were not important either for this variable since any
    letters that were not in the first two variables (but were in the guess) could just simply be added to the String
    and the letters didn't need to be in any specific order or index.
    I chose the StringBuilder, even though concatenation (+) would also work, because when you use concatenation inside
    a loop the String is copied each time you want to add another letter to it, which is inefficient. Using the String
    Builder class allows you to simply append a single letter to a string without copying and creating a new String
    object.
     */

    public HintGenerator(String guess, String secretWord) {
        // Constructor, sets 3 instance variables based on the accuracy of the user input (guess) vs. secret word.
        this.guess = guess; // Sets instance variable equal to token (guess) to give Hint class access to it.
        guess = guess.toLowerCase();
        StringBuilder notInWord = new StringBuilder();

        if (guess.equals(secretWord)) {
            correctlyPlaced = guess; // If guess is a match, no need to go further.
            incorrectlyPlaced = Character.toString('-').repeat(guess.length());
        }
        else {
            char[] correctPlaceArray = new char[secretWord.length()]; // Creates a hint the length of the sec word.
            char[] incorrectPlaceArray = new char[secretWord.length()];
            boolean charPresentElsewhere; // used for incorrectly placed var.
            ArrayList<Integer> prevIndexes = new ArrayList<>(); // keeps track of indexes in secret word so not rec 2x.

            // First loop to check for correctly placed letters.
            for (int i = 0; i < guess.length(); i++) {
                if (guess.charAt(i) == secretWord.charAt(i)) {
                    correctPlaceArray[i] = guess.charAt(i);
                    incorrectPlaceArray[i] = '-';
                    prevIndexes.add(i);
                } else correctPlaceArray[i] = '-';
            }
            // Second step: check for letters in word but wrong location.
            for (int i = 0; i < guess.length(); i++) {
                if (correctPlaceArray[i] != '-') continue; // Already recorded from first loop.
                charPresentElsewhere = false;
                for (int j = 0; j < secretWord.length(); j++) {
                    if (guess.charAt(i) == secretWord.charAt(j) && !prevIndexes.contains(j)) {
                        incorrectPlaceArray[i] = guess.charAt(i);
                        prevIndexes.add(j);
                        charPresentElsewhere = true;
                        break;
                    }
                }
                // Final step: if char in guess but not in word, add to notInPuzzle var.
                if (!charPresentElsewhere) {
                    incorrectPlaceArray[i] = '-';
                    notInWord.append(guess.charAt(i));
                }
            }
            correctlyPlaced = new String(correctPlaceArray); // Changing back to String.
            incorrectlyPlaced = new String(incorrectPlaceArray);
        }
        notInPuzzle = notInWord.toString();
    }

    public boolean isWin() {
        // true iff the '-' isn't in the correctlyPlaced String...
        return (correctlyPlaced.indexOf('-') == -1);
    }

    public void write() {
        // Prints the instance variables (Hints) for user.
        System.out.println("---- Hint (" + guess + ") ----");
        System.out.println("Correctly placed  : " + correctlyPlaced);
        System.out.println("Incorrectly placed: " + incorrectlyPlaced);
        System.out.println("Not in the puzzle : [" + notInPuzzle + "]");
    }

    public String getCorrectlyPlaced() { return correctlyPlaced; } // For testing.

    public String getIncorrectlyPlaced() { return incorrectlyPlaced; }

    public String getNotInPuzzle() { return notInPuzzle; }
}
